export const taskMap = {
    'Введение в JavaScript': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Типы данных и переменные': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Операторы': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Условные конструкции': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Циклы': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Функции': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Массивы': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Объекты': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Работа с датами': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Область видимости (Scope)': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Контекст выполнения (this)': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Классы и ООП': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Асинхронность': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Работа с DOM': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Хранение данных': [
        {
            title: 'Четные числа',
            type: 'code',
            text: `Напишите функцию getEvenNumbers(array), которая принимает на вход массив чисел и возвращает массив, состоящий из четных чисел входного.`,
            xp: 50,
            placeholderCode: `function getEvenNumbers(array) {\n\t// место для вашего кода\n}`,
            tests: [
                { input: [1, 2, 3, 4, 5, 6], expected: [2, 4, 6]},
                { input: [], expected: []},
                { input: [1, 3, 5, 7], expected: []},
                { input: [2, 4, 6, 8], expected: [2, 4, 6, 8]},
            ],
            isSolved: false,
        },
        {
            title: 'Методы массивов',
            type: 'test',
            text: 'Какой метод массива НЕ изменяет исходный массив?',
            xp: 50,
            variants: ['push()', 'splice()', 'slice()', 'sort()'],
            answer: 'slice()',
            isSolved: false,
        }
    ],
    'Основы CSS': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Работа с текстом и шрифтами': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Блочная модель (Box Model)': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Позиционирование и Flexbox': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Grid Layout': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Анимации и трансформации': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Адаптивный дизайн': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'CSS Custom Properties': [
        {
            title: 'Блочность',
            type: 'code',
            text: `Сделайте элементы блочными, задав необходимые стили.`,
            xp: 50,
            placeholderCode: `<span class="element"></span>\n<span class="element"></span>`,
            isSolved: false,
        },
        {
            title: 'Не совсем скрытие',
            type: 'test',
            text: 'Какое свойство скрывает элемент, но оставляет место в разметке?',
            xp: 50,
            variants: ['display: none', 'visibility: hidden', 'opacity: 0', 'width: 0'],
            answer: 'visibility: hidden',
            isSolved: false,
        }
    ],
    'Основы HTML': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Семантическая разметка': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Формы и интерактивные элементы': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Мультимедиа': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Таблицы': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Доступность (a11y)': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Интеграция с API браузера': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
    'Современные API': [
        {
            title: 'Секретный инпут',
            type: 'code',
            text: `Сделайтете input для пароля.`,
            xp: 50,
            placeholderCode: `// место для вашего кода`,
            isSolved: false,
        },
        {
            title: 'Важный текст',
            type: 'test',
            text: 'Какой тег делает текст полужирным и семантически значимым?',
            xp: 50,
            variants: ['<b>', '<strong>', '<i>', '<em>'],
            answer: '<strong>',
            isSolved: false,
        },
    ],
};

